# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:

workspace: "quadcopter"
env_cfg_path: "source/quadcopter/quadcopter/tasks/direct/quadcopter/quadcopter_env.py"
logs_path: "training_logs"
description: "to make the quadcopter reach and hover near a fixed position"


# training settings:
task: Template-Quadcopter-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python

# python scripts/rl_games/train.py --task Template-Quadcopter-Direct-v0 --headless
# python scripts/rl_games/play.py --task Template-Quadcopter-Direct-v0 --num_envs 4
# tensorboard --logdir /home/lee/code/isaactasks/quadcopter/