# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:
# TODO: rearrange the lay out
# workspace: "/home/lee/code/isaactasks/cartpole"
workspace: "cartpole"
env_cfg_path: "source/cartpole/cartpole/tasks/direct/cartpole/cartpole_env.py"
logs_path: "logs/rl_games/cartpole_direct"
description: "to balance a pole on a cart so that the pole stays upright"

# training settings:
task: Template-Cartpole-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
# python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python