# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:

workspace: "masa_hand"
env_cfg_path: "source/masa_hand/masa_hand/tasks/direct/masa_hand/masa_hand_env.py"
logs_path: "logs/rl_games/masa_hand"
description: "to make the masa hand spin the object to a target orientation"

# training settings:
task: Template-Masa-Hand-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python