# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:

workspace: "ant"
env_cfg_path: "source/ant/ant/tasks/direct/ant/ant_env.py"
logs_path: "training_logs"
description: "to make the ant run forward as fast as possible"


# training settings:
task: Template-Ant-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python


# python scripts/rl_games/train.py --task Template-Ant-Direct-v0 --headless