# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:

workspace: "humanoid"
env_cfg_path: "source/humanoid/humanoid/tasks/direct/humanoid/humanoid_env.py"
logs_path: "training_logs"
description: "to make the humanoid run as fast as possible"


# training settings:
task: Template-Humanoid-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python


# python scripts/rl_games/train.py --task Template-Humanoid-Direct-v0 --headless
# tensorboard --logdir humanoid/